In [9]:
import os.path
import pandas

In [11]:
all_data = None

for day in range(1, 31):
    filename = f'options-data/bb_options_201903{day:02d}.csv'
    
    if os.path.isfile(filename):
        day_data = pandas.read_csv(filename)
        day_data['QuoteDate'] = f'03/{day:02d}/2019'

        if all_data is None:
            all_data = day_data
        else:
            all_data = all_data.append(day_data)

all_data

,UnderlyingSymbol,UnderlyingPrice,Exchange,OptionRoot,OptionExt,Type,Expiration,DataDate,Strike,Last,Bid,Ask,Volume,OpenInterest,T1OpenInterest,QuoteDate
0,T,30.82,*,T190301C00022000,NaN,call,03/01/2019,03/01/2019,22.0,0.00,8.05,9.85,0,0,0,03/01/2019
1,T,30.82,*,T190301P00022000,NaN,put,03/01/2019,03/01/2019,22.0,0.01,0.00,0.02,0,5,0,03/01/2019
2,T,30.82,*,T190301C00023000,NaN,call,03/01/2019,03/01/2019,23.0,6.79,7.75,8.10,0,1,0,03/01/2019
3,T,30.82,*,T190301P00023000,NaN,put,03/01/2019,03/01/2019,23.0,0.07,0.00,0.01,0,17,0,03/01/2019
4,T,30.82,*,T190301C00023500,NaN,call,03/01/2019,03/01/2019,23.5,0.00,7.05,8.35,0,0,0,03/01/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,T,31.36,*,T210115P00045000,NaN,put,01/15/2021,03/29/2019,45.0,15.15,14.95,15.85,0,633,633,03/29/2019
806,T,31.36,*,T210115C00047000,NaN,call,01/15/2021,03/29/2019,47.0,0.17,0.14,0.21,0,503,503,03/29/2019
807,T,31.36,*,T210115P00047000,NaN,put,01/15/2021,03/29/2019,47.0,17.00,16.55,17.95,0,143,143,03/29/2019
808,T,31.36,*,T210115C00050000,NaN,call,01/15/2021,03/29/2019,50.0,0.10,0.10,0.12,203,4873,4969,03/29/2019
809,T,31.36,*,T210115P00050000,NaN,put,01/15/2021,03/29/2019,50.0,21.20,19.00,21.30,0,388,388,03/29/2019